/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Exams": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GraphqlApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "OpenAIApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwilioAccountSid": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwilioAuthToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwilioWebhook": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "TwilioWhatsappFrom": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}